const quoteText = $(".quote-text");
const quoteAuthor = $(".quote-author");

quoteText.text("");
quoteAuthor.text("");

const ratingParam = $(".rating-param");
const quoteId = $(".quote-id");
const nextQuote = $(".get-quote");
const tweetButton = $(".tweet");
const quoteRating = $(".rating-text");
const witzig = $(".witzig");
const nichtWitzig = $(".nicht-witzig");

const id_regex = /^\d{1,4}-\d{1,4}$/; //1234-1234

$(document).ready(function () {
    $('select').niceSelect();
});

const ratingSource = "bewertung_zitate.json";
const authorsSource = "namen.txt";
const quotesSource = "zitate.txt";

let authorsArr = [];
let quotesArr = [];
let ratingJson = null;

let id;

const app = $.sammy(function() {
    this.get("#/:id", function() {
        id = this.params["id"];
        displayZitat();
    });

    this.get("/", function () {
        checkId();
    });

    this.get("/#", function () {
        checkId();
    });
});
app.run();

function hasLoaded() {
    return authorsArr.length > 0 && quotesArr.length > 0 && ratingJson !== null;
}

function saveAsImg() {
    html2canvas(document.getElementById('quote-important'), {scrollX: 0,scrollY: -window.scrollY, allowTaint: true, backgroundColor: "#000000"}).then(function (canvas) {
        let a = document.createElement("a"); //Create <a>
        a.href = canvas.toDataURL('image/png').replace('image/png', 'image/octet-stream'); //Image Base64
        a.download = "Zitat_(" + id + ")_asozialesnetzwerk.github.io.png"; //File name
        a.click(); //Downloaded file
    });
}

function changeVisibility(element, visible) {
    const isInvisible = element.hasClass("invisible");
    if(visible === !isInvisible) {
        return;
    }
    if(visible && isInvisible) {
        element.removeClass("invisible");
    } else if (!visible && !isInvisible) {
        element.addClass("invisible");
    }
}

let oldRating;
function displayZitat() {
    checkId();
    if(!hasLoaded()) return;
    nextQuote.attr("href", getNewZitatUrl());

    const ids = id.split("-");
    
    let theQuote = quotesArr[ids[0]] ;
    const theAuthor = authorsArr[ids[1]];
    theQuote = "»" + theQuote.substr(1, theQuote.lastIndexOf('"') - 1) + "«";

    const rating = ((ratingJson[id] === undefined) ? 0 : ratingJson[id]);
    
    quoteText.text(theQuote);
    quoteText.attr("onClick", "window.open('https://ddg.gg/?q=" +  encodeURIComponent(theQuote) + "')");
    quoteAuthor.text("- " + theAuthor);
    quoteAuthor.attr("onClick", "window.open('https://ddg.gg/?q=" +  encodeURIComponent(theAuthor) + "')");

    $('meta[property="og:description"]').remove();
    $('head').append('<meta property="og:description" content=\'' + theQuote + '\n- ' + theAuthor + '\'>' );

    quoteId.text(id);
    if(rating !== oldRating) {
        quoteRating.text(rating === 0 ? "—" : Math.abs(rating) + " x   ");
        if( rating === 0) {
            changeVisibility(witzig, false);
            changeVisibility(nichtWitzig, false);
        } else {
            if (rating < 0) {
                changeVisibility(witzig, false);
                changeVisibility(nichtWitzig, true);
            } else {
                changeVisibility(witzig, true);
                changeVisibility(nichtWitzig, false);
            }
        }
    }
    oldRating = rating;

    tweetButton.attr("href", "https://twitter.com/intent/tweet?text=" + encodeURIComponent(theQuote + ' - ' + theAuthor + "\nGenerated by " + window.location.href));
}

function getBaseUrl() {
    let url = window.location.href;
    window.location.href.toLowerCase().replace(/.+\/zitate/, function (match) {
        url =  match + "/#/";
    });
    return url;
}

function getUrlWithId(value) {
    let rating = getRatingParam();
    return getBaseUrl() + value + (rating === "w" || rating === "" ? "" : "?rating=" + rating);
}

function getUrlWithRating(value) {//w; all; rated; n
    return getBaseUrl()  + id + (value === "w" || value === "" ? "" : "?rating=" + value);
}

function getRandomZitatId() {
    return Math.floor(Math.random() * quotesArr.length) + '-' + Math.floor(Math.random() * authorsArr.length);
}

function getNewZitatUrl() {
    const paramRating = getRatingParam();
    if (paramRating === "all") {
        let newId;
        do {
            newId = getRandomZitatId();
        } while (newId === id);
        return getUrlWithId(newId);
    }
    const keys = Object.keys(ratingJson);
    let z;
    do {
        z = Math.floor(Math.random() * keys.length);
    } while ((ratingJson[keys[z]] <= 0 && paramRating === "w") || (ratingJson[keys[z]] >= 0 && paramRating === "n") || (ratingJson[keys[z]] === 0 && paramRating === "rated") || (keys[z] === id)); //Bis richtiges Zitat gefunden
    
    return getUrlWithId(keys[z]);
}

function isValidId(val) {
    if(val === undefined || val === null || id === "") {
        return false;
    }
    if(id_regex.test(val)) {
        if(hasLoaded()) {
            const ids = id.split('-');
            return ids[0] < quotesArr.length && ids[1] < authorsArr.length;
        } else {
            return true;
        }
    } else {
        return false;
    }
}

function checkId() {
    if(!isValidId(id)) {
        if(id !== undefined && id !== null) {
            console.log("Given id (" + id + ") is invalid.");
        }
        window.location = getNewZitatUrl();
    }
}

function checkLoad() {
    if (hasLoaded()) {
        checkId();
        displayZitat();
    }
}

const getAuthor = function (data) {
    authorsArr = data.split(/\n/);
    checkLoad();
};

const getQuote = function (data) {
    quotesArr = data.split(/\n/);
    checkLoad();
};

const getRating = function (data) {
    ratingJson = JSON.parse(data);
    checkLoad();
};

$.get(ratingSource, getRating, 'text');
$.get(authorsSource, getAuthor, 'text');
$.get(quotesSource, getQuote, 'text');

function getRatingParam() {
    if(ratingParam.val() !== null) {
        return ratingParam.val();
    }
    window.location.href.replace(/[?&]+([^=&]+)=([^&]*)/gi, function (m, key, value) {
        if(key === ratingSource) {
            return value;
        }
    });
    return "w";
}

ratingParam.val(getRatingParam());
if(ratingParam.val() === null) {
    window.location = getUrlWithRating("w");
}

ratingParam.change(function () {
    window.location = getUrlWithRating(getRatingParam());
});

    
    
    
    
    
    
    
    
    
    
    
var author="579"


var keys = Object.keys(rating);
console.log(keys)

console.log(keys.filter(s=>~s.indexOf("-"+author)));
var rip = keys.filter(s=>~s.indexOf("-"+author)); //contain author

var newarr = {};
for (let [key, value] of Object.entries(rip)) {
    newarr[`"${value}"`] = window.r[0][`${value}`];
}

console.log(newarr);
console.log(Object.values(newarr));

console.log(Math.max(...Object.values(newarr))); //max


//console.log(Object.keys(newarr).find(key => newarr[key] === 7)); //only one result


for (let [key, value] of Object.entries(newarr)) {
    if(`${value}` == Math.max(...Object.values(newarr)))
  {
      //console.log(`${key}`);
    console.log(`${key}`.substring(1, `${key}`.indexOf('-')));
  }
}  
